language: python
python: 3.7

env:
  global:
    - CC_TEST_REPORTER_ID=ae7989e7f7fcccfc4895c9c958e9afb76bee8fcb52e73c3dc1051c9f55592d6a

install: make

before_install:
  - pip install poetry

install:
  - make configure

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT