language: python
python: 3.7

env:
  global:
    - IS_TRAVIS=TRUE
    - CC_TEST_REPORTER_ID=99ec8dad44f3dd1bddde0df0156b72cd02ed5bd3ee9f106bcd6465d95bf32e3c

install: make

before_install:
  - pip install poetry

install:
  - make configure

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT